config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/posts/new', to:  'posts#new'
  

  resources :users
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  # has_many :comments
  validates_presence_of :user_id
  validates_length_of :body, maximum: 150
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username
  validates_presence_of :password
  validates_presence_of :email
  has_many :posts
  #has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :current_user

  protected
    def current_user
      # @current_user = User.find(session[:id]) if @user.nil? && session[:id]
      session[:user_id] ? User.find(session[:user_id]) : nil
    # redirect_to(new_user_path) unless current_user
    end

    def login_required
      return true if @user
      access_denied
      return false
    end
  end


    def access_denied
      session[:return_to] = request.request_url
      flash[:error] = 'Ooops! lets login first.'
      redirect_to :conroller => 'user', :action => 'login'
    end



  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  # helper_method :current_user;

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@user = current_user
		@post = Post.new
	end

	def create
	@user= current_user
	@post = Post.create(post_params)
	redirect_to posts_path
	end

	def show
		puts params.inspect
		# @user = User.find(session[:user_id])
		# @signed_in_user = session[:user_id]
		@post = Post.find(params[:id])
		# @posts = @user.posts
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		post.update(post_params)
		redirect_to post_path
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.delete
    redirect_to user_path
	  end
end

private
def post_params
	params.require(:post).permit(:body).merge(user_id: current_user.id)
end

# on the comments controller:
# @post=Post.first	brings

# @post - Post.find(params[post_id])
# @comment = @post.comments.build(comment_params)
# @comment.user = current_user
# @comment.save
# redirect to post_path(@post)

# private
# def comment_params
# 	params.require(:comment).permit(:content)
# end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		@user=User.where(username: params[:username]).first
		if @user && @user.password == params[:password]
			session[:user_id]= @user.id
#A session has been created for that user
			redirect_to user_path(@user)
		else
			redirect_to root_path
		end
	end

		def destroy
			sesion[:user_id] = nil
			redirect_to root_path
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new

	end

	def create
		@user = User.create(user_params)
		# if user params aren't nil, save @user
	  if @user.save
			session[:user_id]= @user.id
	    redirect_to users_path
	  else
	  	redirect_to new_user_path
	  end
	end

	def current_user
		@current_user = session[:user_id]
	end


	def show
	        @user=User.find(params[:id])
	        @posts = Post.where(user_id: @user.id)
	    end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
		 redirect_to @user
		else
		 redirect_to(edit_path)
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		session.destroy

	 redirect_to users_path
 end

	def user_params
		params.require(:user).permit(:username, :password, :email)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# def current_user
# 	@current_user ||

# end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamSpiritApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/.scss" href="welcome.scss">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>list all posts</h1>
<% @posts.each do |post| %>
<h2><%= link_to "#{post.body}", post_path(post) %></h2>
<% end %>
</table>

app/views/posts/new.html.erb
<%= @user.username %>

<h1>new post</h1>
<%= form_for(@post) do |form| %>
<%= form.label :body %>
<%= form.text_field :body %>
<%= form.submit %>
<%end%>

app/views/posts/show.html.erb
<h2><%= @post.body %></h2>
  <p><%= @post.user.username %></p>
<h1>Show A Single Post</h1>
<h3><%= link_to("back to all posts", posts_path) %></h3>
<h4><%= link_to("new post", new_post_path) %></h4>
<%= link_to 'delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/user/show.html.erb
<!-- Page to show the logged-in @user -->
<h2>Welcome<%=username%></h2>

<p>you are logged in</p>
<!-- link to create post -->
<%#link_to new_post%>
<!-- link to edit page -->
<!-- link to delete delete page-->

app/views/users/edit.html.erb
<h1>Update or delete your account" <%= @user.username %></h1>
<%= form_for @user do |form| %>
<%= form.label @user :username %>
<%= form.text_field :username, placeholder: @user.username %>
<%= form.label @user :email %>
<%= form.text_field :email, placeholder: @user.email %>
<%= form.label @user :password %>
<%= form.text_field @user :password, placeholder: @user.password %>
<%= form.submit "save changes" %>
</form>
<% end %>

app/views/users/index.html.erb
<h1>all users</h1>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_path(user) %>
    <%#= link_to "edit", edit_user_path(user) %>
  </li>
  <% end %>

app/views/users/new.html.erb
<h1>You've joined our cult, <%=@user.username%>!</h1>

<br>
<%#= link_to "Edit Your Account", edit_user_path(@user)%>
<!-- <h3>Edit Your Account</h3> <p>(link to users/views/edit.html.erb)</p> -->
<%= link_to "Delete You Account", @user, method: :delete %>
<br>
<%= link_to "Create a Post", new_post_path(@post)%>
<!-- <h3>Create a Post </h3>(link to posts/views/new.html.erb)(the posts/views/new.html.erb has a link to see the single post on posts/views/show.html.erb) -->
<h3>See your Feed</h3>(link to posts/views/index.html.erb)

app/views/users/show.html.erb
<!-- Page to show the logged-in @user -->

<h5>Log Out</h5>
<h2>Welcome: <%=@user.username%></h2>

    <% @posts.each do |post| %>
    <p><%= post.body %></p>
    <%end%>
    
<br>
<%= link_to "Edit Your Account", edit_user_path(@user)%>
<br>

<%= link_to "Delete You Account", @user, method: :delete %>
<br>
<%= link_to "Create a Post", new_post_path(@post)%>

 <%= @user.email %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome, We are TeamSpirit!</h1>

<h2>Log In</h2>
<br>
<%=form_tag login_path do %>
<%=label_tag(:username)%>
<%=text_field_tag(:username)%>
<%=label_tag(:password)%>
<%=password_field_tag(:password)%>
<%=submit_tag "Log In"%>
<%end%>

<!-- Or, Sign Up -->
<!-- SignUp Form Here -->
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :email%>
<%= f.text_field :email%>
<%= f.label :password%>
<%= f.password_field :password%>
<%=f.submit :create %>
<% end %>
<!-- This page would also hold any login error messages from validation failures:
<%# if @user.errors.full_messages.any?%>
<ul>
<%# @user.errors.full_messages.each do |error| %> List each error
<li><%#=error_message%></li><br>/>
<#% end %>
-->